### DATA ###

Muon_Run2022C:
  era: "2022"
  type: data
  group: "data"
  db: das:/Muon/Run2022C-22Sep2023-v1/NANOAOD
  run_range: &runs_22C [355794, 357486]
  certified_lumi_file: &lumi_cert_22 https://cms-service-dqmdc.web.cern.ch/CAF/certification/Collisions22/Cert_Collisions2022_355100_362760_Golden.json
  split: &nsplit -2

Muon_Run2022D:
  era: "2022"
  type: data
  group: "data"
  db: das:/Muon/Run2022D-22Sep2023-v1/NANOAOD
  run_range: &runs_22D [357487, 359021]
  certified_lumi_file: *lumi_cert_22
  split: *nsplit

Muon_Run2022F:
  era: "2022EE"
  type: data
  group: "data"
  db: das:/Muon/Run2022F-22Sep2023-v2/NANOAOD
  run_range: &runs_22F [360332, 362180]
  certified_lumi_file: *lumi_cert_22
  split: *nsplit

Muon_Run2022G:
  era: "2022EE"
  type: data
  group: "data"
  db: das:/Muon/Run2022G-22Sep2023-v1/NANOAOD
  run_range: &runs_22G [362350, 362760]
  certified_lumi_file: *lumi_cert_22
  split: *nsplit

EGamma_Run2022C:
  era: "2022"
  type: data
  group: "data"
  db: das:/EGamma/Run2022C-22Sep2023-v1/NANOAOD
  run_range: *runs_22C
  certified_lumi_file: *lumi_cert_22
  split: *nsplit

EGamma_Run2022D:
  era: "2022"
  type: data
  group: "data"
  db: das:/EGamma/Run2022D-22Sep2023-v1/NANOAOD
  run_range: *runs_22D
  certified_lumi_file: *lumi_cert_22
  split: *nsplit

EGamma_Run2022F:
  era: "2022EE"
  type: data
  group: "data"
  db: das:/EGamma/Run2022F-22Sep2023-v1/NANOAOD
  run_range: *runs_22F
  certified_lumi_file: *lumi_cert_22
  split: *nsplit

EGamma_Run2022G:
  era: "2022EE"
  type: data
  group: "data"
  db: das:/EGamma/Run2022G-22Sep2023-v2/NANOAOD
  run_range: *runs_22G
  certified_lumi_file: *lumi_cert_22
  split: *nsplit

MuonEG_Run2022C:
  era: "2022"
  type: data
  group: "data"
  db: das:/MuonEG/Run2022C-22Sep2023-v1/NANOAOD
  run_range: *runs_22C
  certified_lumi_file: *lumi_cert_22
  split: *nsplit

MuonEG_Run2022D:
  era: "2022"
  type: data
  group: "data"
  db: das:/MuonEG/Run2022D-22Sep2023-v1/NANOAOD
  run_range: *runs_22D
  certified_lumi_file: *lumi_cert_22
  split: *nsplit

MuonEG_Run2022F:
  era: "2022EE"
  type: data
  group: "data"
  db: das:/MuonEG/Run2022F-22Sep2023-v1/NANOAOD
  run_range: *runs_22F
  certified_lumi_file: *lumi_cert_22
  split: *nsplit

MuonEG_Run2022G:
  era: "2022EE"
  type: data
  group: "data"
  db: das:/MuonEG/Run2022G-22Sep2023-v1/NANOAOD
  run_range: *runs_22G
  certified_lumi_file: *lumi_cert_22
  split: *nsplit

DoubleMuon_Run2022C:
  era: "2022"
  type: data
  group: "data"
  db: das:/DoubleMuon/Run2022C-22Sep2023-v1/NANOAOD
  run_range: *runs_22C
  certified_lumi_file: *lumi_cert_22
  split: *nsplit

SingleMuon_Run2022C:
  era: "2022"
  type: data
  group: "data"
  db: das:/SingleMuon/Run2022C-22Sep2023-v1/NANOAOD
  run_range: *runs_22C
  certified_lumi_file: *lumi_cert_22
  split: *nsplit

## MC ###

TTto2L2Nu_TuneCP5_13p6TeV_powheg-pythia8:
  dbs:
    "2022":
      [
        das:/TTto2L2Nu_TuneCP5_13p6TeV_powheg-pythia8/Run3Summer22NanoAODv12-130X_mcRun3_2022_realistic_v5-v2/NANOAODSIM,
        das:/TTto2L2Nu_TuneCP5_13p6TeV_powheg-pythia8/Run3Summer22NanoAODv12-130X_mcRun3_2022_realistic_v5_ext1-v2/NANOAODSIM,
      ]
    "2022EE":
      [
        das:/TTto2L2Nu_TuneCP5_13p6TeV_powheg-pythia8/Run3Summer22EENanoAODv12-130X_mcRun3_2022_realistic_postEE_v6-v2/NANOAODSIM,
        das:/TTto2L2Nu_TuneCP5_13p6TeV_powheg-pythia8/Run3Summer22EENanoAODv12-130X_mcRun3_2022_realistic_postEE_v6_ext1-v2/NANOAODSIM,
      ]
  type: mc
  group: "TTbar"
  cross-section: 98.036113
  generated-events: genEventSumw
  split: *nsplit

TTtoLNu2Q_TuneCP5_13p6TeV_powheg-pythia8:
  dbs:
    "2022":
      [
        das:/TTtoLNu2Q_TuneCP5_13p6TeV_powheg-pythia8/Run3Summer22NanoAODv12-130X_mcRun3_2022_realistic_v5-v2/NANOAODSIM,
        das:/TTtoLNu2Q_TuneCP5_13p6TeV_powheg-pythia8/Run3Summer22NanoAODv12-130X_mcRun3_2022_realistic_v5_ext1-v2/NANOAODSIM,
      ]
    "2022EE":
      [
        das:/TTtoLNu2Q_TuneCP5_13p6TeV_powheg-pythia8/Run3Summer22EENanoAODv12-130X_mcRun3_2022_realistic_postEE_v6-v2/NANOAODSIM,
        das:/TTtoLNu2Q_TuneCP5_13p6TeV_powheg-pythia8/Run3Summer22EENanoAODv12-130X_mcRun3_2022_realistic_postEE_v6_ext1-v2/NANOAODSIM,
      ]
  type: mc
  group: "TTbar"
  cross-section: 405.74553
  generated-events: genEventSumw
  split: *nsplit

DYJetsToLL_M-50_TuneCP5_13p6TeV-madgraphMLM-pythia8:
  dbs:
    "2022": das:/DYJetsToLL_M-50_TuneCP5_13p6TeV-madgraphMLM-pythia8/Run3Summer22NanoAODv12-130X_mcRun3_2022_realistic_v5-v2/NANOAODSIM,
    "2022EE": das:/DYJetsToLL_M-50_TuneCP5_13p6TeV-madgraphMLM-pythia8/Run3Summer22EENanoAODv12-130X_mcRun3_2022_realistic_postEE_v5-v2/NANOAODSIM,
  type: mc
  group: "DY"
  cross-section: 5659
  generated-events: genEventSumw
  split: *nsplit

DYto2L-2Jets_MLL-10to50_TuneCP5_13p6TeV_amcatnloFXFX-pythia8:
  dbs:
    "2022": das:/DYto2L-2Jets_MLL-10to50_TuneCP5_13p6TeV_amcatnloFXFX-pythia8/Run3Summer22NanoAODv12-130X_mcRun3_2022_realistic_v5-v2/NANOAODSIM
    "2022EE": das:/DYto2L-2Jets_MLL-10to50_TuneCP5_13p6TeV_amcatnloFXFX-pythia8/Run3Summer22EENanoAODv12-130X_mcRun3_2022_realistic_postEE_v6-v2/NANOAODSIM
  type: mc
  group: "DY"
  cross-section: 19982.5
  generated-events: genEventSumw
  split: -25

WW_TuneCP5_13p6TeV_pythia8:
  dbs:
    "2022": das:/WW_TuneCP5_13p6TeV_pythia8/Run3Summer22NanoAODv12-130X_mcRun3_2022_realistic_v5-v2/NANOAODSIM
    "2022EE": das:/WW_TuneCP5_13p6TeV_pythia8/Run3Summer22EENanoAODv12-130X_mcRun3_2022_realistic_postEE_v6-v2/NANOAODSIM
  type: mc
  group: "VV"
  cross-section: 80.18
  generated-events: genEventSumw
  split: *nsplit

WZ_TuneCP5_13p6TeV_pythia8:
  dbs:
    "2022": das:/WZ_TuneCP5_13p6TeV_pythia8/Run3Summer22NanoAODv12-130X_mcRun3_2022_realistic_v5-v2/NANOAODSIM
    "2022EE": das:/WZ_TuneCP5_13p6TeV_pythia8/Run3Summer22EENanoAODv12-130X_mcRun3_2022_realistic_postEE_v6-v2/NANOAODSIM
  type: mc
  group: "VV"
  cross-section: 29.1
  generated-events: genEventSumw
  split: *nsplit

WtoLNu-2Jets_TuneCP5_13p6TeV_amcatnloFXFX-pythia8:
  dbs:
    "2022": das:/WtoLNu-2Jets_TuneCP5_13p6TeV_amcatnloFXFX-pythia8/Run3Summer22NanoAODv12-130X_mcRun3_2022_realistic_v5-v2/NANOAODSIM
    "2022EE": das:/WtoLNu-2Jets_TuneCP5_13p6TeV_amcatnloFXFX-pythia8/Run3Summer22EENanoAODv12-130X_mcRun3_2022_realistic_postEE_v6-v2/NANOAODSIM
  type: mc
  group: "WJets"
  cross-section: 67710.0
  generated-events: genEventSumw
  split: -25

ZZ_TuneCP5_13p6TeV_pythia8:
  dbs:
    "2022": das:/ZZ_TuneCP5_13p6TeV_pythia8/Run3Summer22NanoAODv12-130X_mcRun3_2022_realistic_v5-v2/NANOAODSIM
    "2022EE": das:/ZZ_TuneCP5_13p6TeV_pythia8/Run3Summer22EENanoAODv12-130X_mcRun3_2022_realistic_postEE_v6-v2/NANOAODSIM
  type: mc
  group: "VV"
  cross-section: 12.75
  generated-events: genEventSumw
  split: *nsplit

# TW cross section from: https://cms-talk.web.cern.ch/t/new-jecs-for-run3-prompt-fg-eras/26529
TbarWplusto2L2Nu_TuneCP5_13p6TeV_powheg-pythia8:
  dbs:
    "2022":
      [
        das:/TbarWplusto2L2Nu_TuneCP5_13p6TeV_powheg-pythia8/Run3Summer22NanoAODv12-130X_mcRun3_2022_realistic_v5-v2/NANOAODSIM,
        das:/TbarWplusto2L2Nu_TuneCP5_13p6TeV_powheg-pythia8/Run3Summer22NanoAODv12-130X_mcRun3_2022_realistic_v5_ext1-v2/NANOAODSIM,
      ]
    "2022EE":
      [
        das:/TbarWplusto2L2Nu_TuneCP5_13p6TeV_powheg-pythia8/Run3Summer22EENanoAODv12-130X_mcRun3_2022_realistic_postEE_v6-v2/NANOAODSIM,
        das:/TbarWplusto2L2Nu_TuneCP5_13p6TeV_powheg-pythia8/Run3Summer22EENanoAODv12-130X_mcRun3_2022_realistic_postEE_v6_ext1-v2/NANOAODSIM,
      ]
  type: mc
  group: "TW"
  cross-section: 4.6651009 # xsec(TW) / 2 (since t and tbar is included) x BR(W->l nu)^2 x 2 (since there are two W bosons) = 87.9 / 2 x 0.3259^2 x 2
  generated-events: genEventSumw
  split: *nsplit

TbarWplustoLNu2Q_TuneCP5_13p6TeV_powheg-pythia8:
  dbs:
    "2022":
      [
        das:/TbarWplustoLNu2Q_TuneCP5_13p6TeV_powheg-pythia8/Run3Summer22NanoAODv12-130X_mcRun3_2022_realistic_v5-v2/NANOAODSIM,
        das:/TbarWplustoLNu2Q_TuneCP5_13p6TeV_powheg-pythia8/Run3Summer22NanoAODv12-130X_mcRun3_2022_realistic_v5_ext1-v2/NANOAODSIM,
      ]
    "2022EE":
      [
        das:/TbarWplustoLNu2Q_TuneCP5_13p6TeV_powheg-pythia8/Run3Summer22EENanoAODv12-130X_mcRun3_2022_realistic_postEE_v6-v2/NANOAODSIM,
        das:/TbarWplustoLNu2Q_TuneCP5_13p6TeV_powheg-pythia8/Run3Summer22EENanoAODv12-130X_mcRun3_2022_realistic_postEE_v6_ext1-v2/NANOAODSIM,
      ]
  type: mc
  group: "TW"
  cross-section: 19.307618 # xsec(TW) / 2 (since t and tbar is included) x BR(W->l nu) x BR(W->qq) x 2 (since there are two W bosons) = 87.9 / 2 x 0.3259 x 0.6741
  generated-events: genEventSumw
  split: *nsplit

TWminusto2L2Nu_TuneCP5_13p6TeV_powheg-pythia8:
  dbs:
    "2022":
      [
        das:/TWminusto2L2Nu_TuneCP5_13p6TeV_powheg-pythia8/Run3Summer22NanoAODv12-130X_mcRun3_2022_realistic_v5-v2/NANOAODSIM,
        das:/TWminusto2L2Nu_TuneCP5_13p6TeV_powheg-pythia8/Run3Summer22NanoAODv12-130X_mcRun3_2022_realistic_v5_ext1-v2/NANOAODSIM,
      ]
    "2022EE":
      [
        das:/TWminusto2L2Nu_TuneCP5_13p6TeV_powheg-pythia8/Run3Summer22EENanoAODv12-130X_mcRun3_2022_realistic_postEE_v6-v2/NANOAODSIM,
        das:/TWminusto2L2Nu_TuneCP5_13p6TeV_powheg-pythia8/Run3Summer22EENanoAODv12-130X_mcRun3_2022_realistic_postEE_v6_ext1-v2/NANOAODSIM,
      ]
  type: mc
  group: "TW"
  cross-section: 4.6651009
  generated-events: genEventSumw
  split: *nsplit

TWminustoLNu2Q_TuneCP5_13p6TeV_powheg-pythia8:
  dbs:
    "2022":
      [
        das:/TWminustoLNu2Q_TuneCP5_13p6TeV_powheg-pythia8/Run3Summer22NanoAODv12-130X_mcRun3_2022_realistic_v5-v2/NANOAODSIM,
        das:/TWminustoLNu2Q_TuneCP5_13p6TeV_powheg-pythia8/Run3Summer22NanoAODv12-130X_mcRun3_2022_realistic_v5_ext1-v2/NANOAODSIM,
      ]
    "2022EE":
      [
        das:/TWminustoLNu2Q_TuneCP5_13p6TeV_powheg-pythia8/Run3Summer22EENanoAODv12-130X_mcRun3_2022_realistic_postEE_v6-v2/NANOAODSIM,
        das:/TWminustoLNu2Q_TuneCP5_13p6TeV_powheg-pythia8/Run3Summer22EENanoAODv12-130X_mcRun3_2022_realistic_postEE_v6_ext1-v2/NANOAODSIM,
      ]
  type: mc
  group: "TW"
  cross-section: 19.307618
  generated-events: genEventSumw
  split: *nsplit
