image: gitlab-registry.cern.ch/ci-tools/ci-worker:cc7

stages:
  - build
  - test
  - deploy

variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
cache:
  paths:
    - .cache/pip
    - tests/data/JECDatabase
    - tests/data/JRDatabase

build_102: # LCG_102, ROOT 6.26, newest version
  tags: [k8s-cvmfs]
  stage: build
  before_script:
    - yum install -y libgfortran make atlas
    - source /cvmfs/sft.cern.ch/lcg/views/LCG_102/x86_64-centos7-gcc11-opt/setup.sh
    - python -m venv venv102
    - source venv102/bin/activate
  artifacts:
    paths: [venv102]
    expire_in: 30min
  script:
    # NOTE 'pre-commit -a' can be used (with all the checks) from LCG_102 on
    # NOTE see https://sft.its.cern.ch/jira/browse/SPI-1978
    - python -m pip install flake8 flake8-bugbear
    - flake8 --exclude=venv102/
    - python -m pip install scikit-build
    - python -m pip install git+https://gitlab.cern.ch/cp3-cms/CMSJMECalculators.git
    - python -m pip install . --no-build-isolation # with libtorch
test_102:
  tags: [k8s-cvmfs]
  stage: test
  needs: [build_102]
  before_script:
    - source /cvmfs/sft.cern.ch/lcg/views/LCG_102/x86_64-centos7-gcc11-opt/setup.sh
    - source venv102/bin/activate
  script:
    - cd tests
    - pytest --junitxml=report_102.xml
  artifacts:
    paths: [tests/report_102.xml]
    reports:
      junit: tests/report_102.xml

